### ISSUE TITLE
Error when exponentiating an attribute [Neovim]

### ISSUE THREAD

**Issue by ctallec** [davidhalter/jedi#1268]
Under neovim, using deoplete, jedi and deoplete-jedi, Jedi crashes when trying to perform dot completion on expressions of the form (self.attr ** number).

I'm attaching a minimal init.vim a python file that lead to the error, a recap of the version of neovim I am using as well as the error log. I am using python 3.7.0. 
The error occurs right after trying to use dot completion.

[err.log](https://github.com/davidhalter/jedi/files/2702353/err.log)
[fault.py.txt](https://github.com/davidhalter/jedi/files/2702359/fault.py.txt)
[init.vim.txt](https://github.com/davidhalter/jedi/files/2702360/init.vim.txt)
[nvim_version.txt](https://github.com/davidhalter/jedi/files/2702372/nvim_version.txt)

If someone has time to look into that, I would be grateful,

Thanks in advance !

**Comment by davidhalter** [comment]
Can you please try the typeshed branch? I feel like we fixed this this year. I cannot reproduce it anymore and it feels good.

Next time, please give us the Jedi version you are using.

**Comment by ctallec** [comment]
The error seems to persist, even after switching to the typeshed branch. I checked out the typeshed branch in the .vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/ directory, which seems to be where deoplete-jedi clones its version of jedi, but I'm still getting a similar error. I'm linking the log file below. Could this be related to deoplete-jedi or deoplete ?
[err.log](https://github.com/davidhalter/jedi/files/2706413/err.log)

**Comment by davidhalter** [comment]
I can reproduce now, thanks!!

**Comment by davidhalter** [comment]
Thank you for the report!

**Comment by ctallec** [comment]
Works perfectly now ! Thanks a lot ! I'm amazed by your reactivity !
