### ISSUE TITLE
Python 3.13 compatible release

### ISSUE THREAD

**Issue by bstaletic** [davidhalter/jedi#2026]
Will there soon be a release that allows jedi to work with python 3.13?
I'm not too affected, as ycmd is using jedi as a submodule, so we can pin to whatever commit, but it would be the first time we'd not be pinning to a tag.

Either way, thanks for maintaining jedi for so long.

**Comment by davidhalter** [comment]
I released a new version with Python 3.13 support. Please let me know if there are issues.

**Comment by bstaletic** [comment]
A bit of a late response, but I've been using jedi with python 3.13 for a while and things are working great.

**Comment by 0x74h51N** [comment]
Hey, I'm still hitting pickle errors on Python 3.13.11 (Fedora 42) with jedi 0.19.2.
Using jedi in Kate editor. When I scroll through Python files, jedi keeps throwing `_pickle.UnpicklingError`. It seems like the subprocess stdout gets corrupted data and pickle can't parse it.

 ## Environment
> - Python: 3.13.11 (Fedora 42)
> - jedi: 0.19.2
> - jedi-language-server: 0.46.0
> - Editor: Kate 25.12.2 (LSP client)

## Traceback
```
ERROR:pygls.protocol.json_rpc:Exception occurred for message "83"
Traceback (most recent call last):
  File "/home/0x74h51n/.local/lib/python3.13/site-packages/pygls/protocol/json_rpc.py", line 300, in _send_handler_result
    self._send_response(msg_id, result=future.result())
                                       ~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib64/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/0x74h51n/.local/lib/python3.13/site-packages/jedi_language_server/server.py", line 878, in semantic_tokens_range
    return _semantic_tokens_range(server, jedi_script, params.range)
  File "/home/0x74h51n/.local/lib/python3.13/site-packages/jedi_language_server/server.py", line 899, in _semantic_tokens_range
    token = _raw_semantic_token(server, n)
  File "/home/0x74h51n/.local/lib/python3.13/site-packages/jedi_language_server/server.py", line 798, in _raw_semantic_token
    definitions: list[Name] = n.goto(
                              ~~~~~~^
        follow_imports=True,
        ^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        prefer_stubs=False,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib64/python3.13/contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.13/site-packages/jedi/api/classes.py", line 445, in goto
    names = self._name.goto()
  File "/usr/lib/python3.13/site-packages/jedi/inference/names.py", line 157, in goto
    module_names = goto_import(context, name)
  File "/usr/lib/python3.13/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/jedi/inference/imports.py", line 75, in goto_import
    _prepare_infer_import(module_context, tree_name)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/jedi/inference/imports.py", line 116, in _prepare_infer_import
    return from_import_name, tuple(import_path), import_node.level, importer.follow()
                                                                    ~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/jedi/inference/imports.py", line 296, in follow
    return import_module_by_names(
        self._inference_state, self.import_path, sys_path, self._module_context
    )
  File "/usr/lib/python3.13/site-packages/jedi/inference/imports.py", line 377, in import_module_by_names
    import_module(
    ~~~~~~~~~~~~~^
        inference_state,
        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
        prefer_stubs=prefer_stubs,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) for parent_module_value in value_set
    ^
  File "/usr/lib/python3.13/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/jedi/plugins/flask.py", line 20, in wrapper
    return callback(inference_state, import_names, module_context, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/jedi/inference/gradual/typeshed.py", line 115, in wrapper
    python_value_set = ValueSet.from_sets(
        func(inference_state, import_names, p, sys_path,)
        for p in parent_module_values
    )
  File "/usr/lib/python3.13/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
                ^^^^
  File "/usr/lib/python3.13/site-packages/jedi/inference/gradual/typeshed.py", line 116, in <genexpr>
    func(inference_state, import_names, p, sys_path,)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/jedi/inference/imports.py", line 411, in import_module
    file_io_or_ns, is_pkg = inference_state.compiled_subprocess.get_module_info(
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        string=import_names[-1],
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        is_global_search=True,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/jedi/inference/compiled/subprocess/__init__.py", line 188, in wrapper
    result = self._compiled_subprocess.run(
        self._inference_state_id,
    ...<2 lines>...
        kwargs=kwargs,
    )
  File "/usr/lib/python3.13/site-packages/jedi/inference/compiled/subprocess/__init__.py", line 296, in run
    return self._send(inference_state_id, function, args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/jedi/inference/compiled/subprocess/__init__.py", line 318, in _send
    is_exception, traceback, result = pickle_load(self._get_process().stdout)
                                      ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/jedi/_compatibility.py", line 25, in pickle_load
    return Unpickler(file).load()
           ~~~~~~~~~~~~~~~~~~~~^^
_pickle.UnpicklingError: invalid load key, '/'.
```

**Comment by davidhalter** [comment]
Have you tried deleting the cache? This might just be a one off corruption on hardware level.

If this is reproducible with a fresh cache, it's of course a different story.

**Comment by 0x74h51N** [comment]
> Have you tried deleting the cache? This might just be a one off corruption on hardware level.
> 
> If this is reproducible with a fresh cache, it's of course a different story.

I cleared the Jedi cache and tried again, but the error persists. Also hardware is fine and everything works perfectly in nvim with Jedi. This seems to be specific to how Kate interacts with Jedi. It feels like Kate's lsp client is somehow corrupting the subprocess communication, leading to that UnpicklingError... Anyway, I just wanted to give Kate a try for the sake of the KDE community, but I'm done with it... :d

**Comment by davidhalter** [comment]
I'm happy to assist and try to fix this if it is actually an issue, but I would need a way to reproduce this issue.

**Comment by 0x74h51N** [comment]
> I'm happy to assist and try to fix this if it is actually an issue, but I would need a way to reproduce this issue.

Hey, I’d be happy to help track down this issue. I’ll try to reproduce it with different python versions etc., and try to provide more information. As I understand it, this is not just related to Python 3.13, but seems to be caused by how the Kate LSP client handles Jedi’s communication, so it might not even be related to this repo :D. Also, if you have any suggestion or question, I’m here to help.

**Comment by 0x74h51N** [comment]
I figured it out. Main reason of that error was jedi-language-server... I tried different python versions and servers on venv. jedi-language-server gives this error https://github.com/davidhalter/jedi/issues/2026#issuecomment-3945157407 

Actually it was abvious 
> ...
>    result = self.fn(*self.args, **self.kwargs)
>   File "/home/0x74h51n/.local/lib/python3.13/site-packages/jedi_language_server/server.py", line 878, in semantic_tokens_range
>     return _semantic_tokens_range(server, jedi_script, params.range)
> ...

but it takes time to realize... 

Also in pylsp no error occurs, tooltip info and autocomplete works but highlighting is not working completely. In nvim, jedi-language-server works better, but kate has an issue but is not this repo's issue :d. Sorry...

**Comment by davidhalter** [comment]
What is obvious? On a related note you might want to try out Zuban. It's generally better than Jedi, just not in terms of goto/completions, but that should also improve.

**Comment by 0x74h51N** [comment]
> What is obvious? On a related note you might want to try out Zuban. It's generally better than Jedi, just not in terms of goto/completions, but that should also improve.

My apologies, I just thought the error was being thrown from jedi_language_server/server.py specifically and I also tried other servers and they didn't have this issue with Jedi on Kate (by the way I'm not really a Kate user, I just wanted to give it a try and I just want to move away from microsoft's npm product) and since everything works fine in nvim (even with jedi-language-server), I thought the error isn't about this repo and that is why I said "it was obvious", which I meant it was clearly my mistake to write this issue here in the first place... So I'm no LSP expert, maybe the error is not just about the server or is, idk :D.. I wish I had been clearer about what this error actually is, but I couldn't. Sorry...  Anyway, thanks for your attention, I'll try Zuban :)
