### ISSUE TITLE
completion triggers __get__ side effects.

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#925]
See full description and discussion https://github.com/ipython/ipython/issues/10521#issuecomment-300231012

It should be possible to work around that with [getattr_static](https://docs.python.org/3/library/inspect.html#inspect.getattr_static), but that's python 3 only, it may need a custom backport.

**Comment by bilderbuchi** [comment]
I also ran into this when interacting with hardware. I noticed when the debugging level showed my stuff flying over the serial connection when I was tabbing.

To demonstrate a--in my opinion--legitimate use of `@property` with side-effects, think of the communication for getting and setting values being handled in the getters and setters, yielding
```
>>> motor.position
456
>>> motor.position = 500
>>> motor.position
500
```

**Comment by bilderbuchi** [comment]
[This comment](https://github.com/ipython/ipython/issues/10720#issuecomment-319168402) says this does not happen with Jedi 0.9.0 - is there value in trying to git-bisecting this, or is the `getattr` call linked by @Carreau above definitely the cause?

**Comment by davidhalter** [comment]
I think that a lot of code regarding REPL completion was completely redone in Python 0.10.0. I don't think that bisecting helps.

**Comment by davidhalter** [comment]
I'm currently working on #931. There's an issue regarding `__get__` side effects.

**Comment by bilderbuchi** [comment]
Great, thanks!

**Comment by davidhalter** [comment]
I think now I found a bug in getattr_static, haha.

**Comment by davidhalter** [comment]
This is the bug:

```
class Descriptor:
    def __get__(self, obj, objtype):
        return 'foo'
    
    def __delete__(self, obj):
        print('del', obj)

class X:
    x = Descriptor()

instance = X()
instance.__dict__['x'] = 'bar'
instance.x  # 'foo'

import inspect
inspect.getattr_static(instance, 'x')  # 'bar', should return a `Descriptor` instance
```

getattr_static only checks if `__set__` is part of the descriptor and not if either `__set__` or `__delete__` are set. (Implementation detail: Both of these methods set the same slot called `tp_descr_set` in CPython).

I'll try to report it upstream.

**Comment by bilderbuchi** [comment]
Thanks!

**Comment by davidhalter** [comment]
I fixed it. But I still have issues in Python 2.

**Comment by peterkamatej** [comment]
I also have troubles with the side effects of jedi in Python 3. When the user attempts to TAB-complete my object's attribute, the object starts to read an overwhelming amount of data from our database, which is fatal for the python process (has to be killed). Apparently the auto-completer is not happy with the __dir__ method that I have defined, and instead starts accessing the __getattr__ method which triggers extensive data reading. I assume that your fix with getattr_static should fix this. When can I expect this fix to be released?

**Comment by davidhalter** [comment]
Can you please test if it was fixed in with the getattr_static changes?

It might still take some time until a release will happen. I'm currently trying to release parso first.

**Comment by peterkamatej** [comment]
I'll try to install jedi manually from this repository and test the newest revision in next week.

**Comment by peterkamatej** [comment]
Hi, your change with getattr_static does indeed fix my issues with side effects! So I guess it would be worth releasing even as it is :-). Thanks

**Comment by Will-So** [comment]
I had this problem and I can confirm downgrading to Jedi 0.9.0 fixes the problem. I look forward to the fix but I do still have this issue with Jedi 0.10.0.
